[package]
name = "tempest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
aprilasr = "0.1.2"
cpal = "0.15.2"
lazy_static = "1.4.0"
mouse-keyboard-input = "0.4.1"
