model_path: model.april
wake_phrase: tempest rise
rest_phrase: tempest rest
infer_phrase: tempest listen

actions:
  - phrase: move window focus up
    keys: [super, dot]
  - phrase: move window focus down
    keys: [super, comma]
  - phrase: stack windows
    keys: [super, i]
  - phrase: decouple windows
    keys: [super, o]
  - phrase: exit a windows
    keys: [super, q]
  - phrase: cycle window size
    keys: [super, r]
  - phrase: fullscreen a window
    keys: [super, f]
  - phrase: display quick settings
    keys: [super, s]
  - phrase: escape a modal
    keys: [esc]
  - phrase: open a browser
    command: [librewolf]
  - phrase: open a terminal
    command: [blackbox]
  - phrase: system config
    command: [xdg-open, "/home/h/Public/dotfiles/hosts/default/configuration.nix"]
  - phrase: system rebuild
    command: [pkexec, nixos-rebuild, switch, "--flake", "/home/h/Public/dotfiles#cafe"]

# experimental
ollama_model: mistral
ollama_endpoint: "http://localhost:11434/api/chat"
